/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import principal.Busca;
import principal.Leitura;

/**
 *
 * @author bruno
 */
public class Painel extends javax.swing.JFrame {

    /**
     * Creates new form Painel
     */
    public Painel() {
        initComponents();
        setLocationRelativeTo(null);
        jInicio.setOpaque(true);
        jFinal.setOpaque(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jError = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jInicio = new javax.swing.JLabel();
        jFinal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollSol = new javax.swing.JScrollPane();
        jSolucao = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTexto = new javax.swing.JTextPane();
        jSolucionar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jCusto = new javax.swing.JLabel();
        jNovaBusca = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jFile = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jError.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jError.setTitle("Error");

        jLabel1.setFont(new java.awt.Font("Comfortaa", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Error ao processar o arquivo!");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jErrorLayout = new javax.swing.GroupLayout(jError.getContentPane());
        jError.getContentPane().setLayout(jErrorLayout);
        jErrorLayout.setHorizontalGroup(
            jErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
            .addGroup(jErrorLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jErrorLayout.setVerticalGroup(
            jErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jErrorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInicio.setBackground(new java.awt.Color(0, 102, 0));
        jInicio.setFont(new java.awt.Font("Comfortaa Light", 0, 12)); // NOI18N
        jInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jInicio.setText("Ponto");

        jFinal.setBackground(new java.awt.Color(0, 0, 204));
        jFinal.setFont(new java.awt.Font("Comfortaa Light", 0, 12)); // NOI18N
        jFinal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jFinal.setText("Ponto");

        jLabel3.setFont(new java.awt.Font("Comfortaa Light", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Ponto Inicial:");

        jLabel4.setFont(new java.awt.Font("Comfortaa Light", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Ponto Final:");

        jLabel2.setFont(new java.awt.Font("Comfortaa Light", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Matriz");

        jScrollSol.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jSolucao.setEditable(false);
        jSolucao.setColumns(20);
        jSolucao.setFont(new java.awt.Font("Caviar Dreams", 0, 12)); // NOI18N
        jSolucao.setRows(5);
        jScrollSol.setViewportView(jSolucao);

        jScrollPane2.setViewportView(jTexto);

        jSolucionar.setFont(new java.awt.Font("Comfortaa Light", 0, 12)); // NOI18N
        jSolucionar.setText("Solucionar");
        jSolucionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSolucionarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Custo Final");

        jCusto.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        jCusto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCusto.setText("Custo");
        jCusto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jNovaBusca.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jNovaBusca.setText("Realizar Nova Busca");
        jNovaBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNovaBuscaActionPerformed(evt);
            }
        });

        jFile.setText("File");
        jFile.setFont(new java.awt.Font("Comfortaa Light", 0, 12)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Comfortaa Light", 0, 12)); // NOI18N
        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jFile.add(jMenuItem1);

        jMenuBar1.add(jFile);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jNovaBusca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollSol)
                    .addComponent(jSolucionar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jInicio, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jFinal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSolucionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollSol, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jNovaBusca)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Busca busca;
    private Leitura ler;

    public Leitura getLer() {
        return ler;
    }

    public void setLer(Leitura ler) {
        this.ler = ler;
    }

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.ler = new Leitura();
        if (ler.fileChooser()) {
            jInicio.setText(this.ler.getInicio().toString());
            jFinal.setText(this.ler.getFim().toString());

            this.busca = new Busca(this.ler.getInicio(), this.ler.getFim(), this.ler.getMatriz());

            jTexto.setText(this.ler.getMatriz().toString());

            StyledDocument doc = jTexto.getStyledDocument();
            SimpleAttributeSet center = new SimpleAttributeSet();
            StyleConstants.setAlignment(center, StyleConstants.ALIGN_CENTER);
            doc.setParagraphAttributes(0, doc.getLength(), center, false);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jSolucionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSolucionarActionPerformed
        // TODO add your handling code here:
        if (ler.getMatriz() != null) {
            jSolucao.setText(busca.retornaCaminho());
            jSolucao.setLineWrap(true);
            jSolucao.setWrapStyleWord(true);

            new Thread() {
                @Override
                public void run() {
                    try {
                        View view = new View(busca);
                        view.setVisible(true);
                    } catch (Exception e) {
                    }
                }
            }.start();

            jCusto.setText(String.valueOf(busca.getCaminho().get(busca.getCaminho().size() - 1).getCusto()));
        } else {
            JOptionPane.showMessageDialog(rootPane, "Arquivo não carregado!");
        }
    }//GEN-LAST:event_jSolucionarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.rootPane.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jNovaBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNovaBuscaActionPerformed
        // TODO add your handling code here:
        if (ler != null && ler.getMatriz() != null) {
            Pontos ponto = new Pontos();
            ponto.setVisible(true);
            
            try {
                Thread.sleep(10000L);
            } catch (InterruptedException ex) {
                Logger.getLogger(Painel.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            if (!ponto.hasFocus()) {
                if (ponto.getInicio() != null && ponto.getFim() != null) {
                    this.jInicio.setText(ponto.getInicio().toString());
                    this.jFinal.setText(ponto.getFim().toString());

                    this.busca = new Busca(ponto.getInicio(), ponto.getFim(), this.ler.getMatriz());
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Arquivo não carregado!");
        }
    }//GEN-LAST:event_jNovaBuscaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Painel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jCusto;
    private javax.swing.JFrame jError;
    private javax.swing.JMenu jFile;
    private javax.swing.JLabel jFinal;
    private javax.swing.JLabel jInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JButton jNovaBusca;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollSol;
    private javax.swing.JTextArea jSolucao;
    private javax.swing.JButton jSolucionar;
    private javax.swing.JTextPane jTexto;
    // End of variables declaration//GEN-END:variables
}
